### ISSUE TITLE
Add a package.json file

### ISSUE THREAD

**Issue by oliverzy** [ludovicofischer/mocha-chai-browser-demo#1]
It's better to add a package.json file so that the user can quickly install related packages.
And `karma-mocha-reporter` is a great plugin to show report like mocha runs in Node.js

`
{
  "name": "mocha-chai-browser-demo",
  "version": "1.0.0",
  "description": "A demo setup for unit testing client-side JavaScript code with [Mocha.js](http://visionmedia.github.io/mocha/) and [Chai.js](http://chaijs.com/).",
  "main": "karma.conf.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/ludovicofischer/mocha-chai-browser-demo"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/ludovicofischer/mocha-chai-browser-demo/issues"
  },
  "homepage": "https://github.com/ludovicofischer/mocha-chai-browser-demo",
  "devDependencies": {
    "karma": "^0.12.31",
    "karma-chrome-launcher": "^0.1.7",
    "karma-mocha": "^0.1.10",
    "karma-mocha-reporter": "^0.3.1",
    "mocha": "^2.1.0"
  }
}
`

**Comment by ludofischer** [comment]
Can you make a pull request for this? I guess you already have the code somewhere; I could copy and paste this code, but if you do a pull request Gihtub would credit you with the commit.

Comments on the change itself:  `karma` and `mocha dependencies` are not needed as `karma-mocha` includes them in `peerDependencies`  . For karma-mocha-reporter, and karma-chrome-launcher, you also need to change the karma configuration. I would not want the setup to become too complicated for those that do not know npm, so I am inclined to leave them out. Finally, I would pick the MIT license instead of ISC for familiarity.
